name: my first worklfow
on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v5

      - name: list and read files
        run: |
          echo "my first github actions job" > report.txt
          ls -ltra
          cat report.txt

      - name: install and generate ascii artwork
        run: |
          pip install cowsay
          cowsay -f dragon "Beware of dragons!" >> dragon.txt